### PR TITLE
do not search for service_container references

### LINKED ISSUE #36: You have requested a non-existent service "service_container".
Today my build failed with the error shown above.
https://travis-ci.org/rollerworks/RouteAutowiringBundle/jobs/197594167

It seems something is changed in the way Symfony 3.3 handles the `service_container` service reference. But I cannot find out what exactly.

A simple fix is to simple ignore the `service_container` in `\Matthias\SymfonyServiceDefinitionValidator\ArgumentValidator::validateReferenceArgument` but there should be better fix.

Right now I'm unable to use the validator with Symfony 3.3

### PR DESCRIPTION
**Pull request by xabbuh**
This fixes #36.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Excellent work as always :)

**Comment by craigh** [comment]
this change is now breaking my Symfony-2.8.x application. on `composer-update` I get these errors:
```
 [RuntimeException]                                                                                                                                 
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                          
  Fatal error: Uncaught exception 'Matthias\SymfonyServiceDefinitionValidator\Exception\InvalidServiceDefinitionsException' with message 'Service d  
  efinition validation errors (3):                                                                                                                   
  - zikula_core.internal.doctrine_init: Argument for type-hint "Symfony\Component\DependencyInjection\ContainerBuilder" points to a service of clas  
  s "Symfony\Component\DependencyInjection\Container"                                                                                                
  - hook_dispatcher.servicefactory: Argument for type-hint "Symfony\Component\DependencyInjection\ContainerBuilder" points to a service of class "S  
  ymfony\Component\DependencyInjection\Container"                                                                                                    
  - doctrine_extensions: Argument for type-hint "Zikula\Bridge\DependencyInjection\ContainerBuilder" points to a service of class "Symfony\Componen  
  t\DependencyInjection\Container"' in /Applications/MAMP/htdocs/core.git/src/vendor/matthiasnoback/symfony-service-definition-validator/Compiler/V  
  alidateServiceDefinitionsPass.php:44                                                                                                               
  Stack trace:                                                                                                                                       
  #0 /Applications/MAMP/htdocs/core.git/src/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php( in /Application  
  s/MAMP/htdocs/core.git/src/vendor/matthiasnoback/symfony-service-definition-validator/Compiler/ValidateServiceDefinitionsPass.php on line 44       
  .
```

**Comment by craigh** [comment]
reverting to 1.2.6 removes the errors and the project builds properly.

**Comment by matthiasnoback** [comment]
@xabbuh Any idea how to fix this? The type of `service_container` might
have to be changed to `ContainerInterface`. Not sure if that works though!

On Feb 9, 2017 03:37, "Craig Heydenburg" <notifications@github.com> wrote:

reverting to 1.2.6 removes the errors and the project builds properly.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/matthiasnoback/symfony-service-definition-validator/pull/37#issuecomment-278530011>,
or mute the thread

**Comment by xabbuh** [comment]
@matthiasnoback That won't solve the issue either. The `ContainerBuilder` class is an instance of the `ContainerInterface`. But the check is performed the other way around. That's why it's currently failing as the `Container` class is not an instance of `ContainerBuilder`.

By the way, expecting a `ContainerBuilder` in general is fragile. However, this PR shouldn't indeed have broken that. I will look into how to solve this.

**Comment by craigh** [comment]
> I will look into how to solve this

thank you @xabbuh

**Comment by xabbuh** [comment]
@craigh Is there a test in Zikula I could execute to reproduce the issue?

**Comment by craigh** [comment]
@xabbuh sadly, no. Zikula isn't quite up to spec on proper tests yet.

you can see here: https://github.com/zikula/core/commit/4d6dd49d09cfee20027541c35b4d9f870ad78f57

that I restricted the version. If you revert that and run `composer update` on the repo, then you get the error I showed above

**Comment by sstok** [comment]
Thanks for fixing this 👍 I did not provide a pr because I wasn't sure how to fix this 😅

**Comment by xabbuh** [comment]
As far as I can see there is no way to solve the problem without removing the code that validates the argument type hint (no matter what class we used for the pseudo container definition all would fail when the service expects a `ContainerBuilder` instance).

@matthiasnoback I think we need to drop the type check for the special `service_container` to not break BC. What do you think?

**Comment by matthiasnoback** [comment]
Okay, I would agree with a hard-coded rule to ignore this particular
service, though it's not pretty of course ;)

Another, maybe future solution would be to raise a warning for this kind of
Liskov substitution principle violation. But people wouldn't be able to fix
broken external dependencies anyway so it might not be helpful at all :)

Thanks for your work @xabbuh!

On Feb 12, 2017 20:04, "Christian Flothmann" <notifications@github.com>
wrote:

As far as I can see there is no way to solve the problem without removing
the code that validates the argument type hint (no matter what class we
used for the pseudo container definition all would fail when the service
expects a ContainerBuilder instance).

@matthiasnoback <https://github.com/matthiasnoback> I think we need to drop
the type check for the special service_container to not break BC. What do
you think?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/matthiasnoback/symfony-service-definition-validator/pull/37#issuecomment-279240068>,
or mute the thread

**Comment by xabbuh** [comment]
@matthiasnoback I agree that this solution is not pretty. But since we don't know if people actually do compile the container after it has been build, we don't know if it's safe for them to make these assumptions (like, for example, Zikula seems to always use the `ContainerBuilder` during runtime instead of a previously dumped one).

**Comment by matthiasnoback** [comment]
@xabbuh Okay, seems fine to me then!

**Comment by xabbuh** [comment]
@craigh It looks like even if we make the change I suggested above, you will run into the same problems due to the `ContainerInterface` being registered as a definition in 3.3 (see symfony/symfony#21627)

**Comment by xabbuh** [comment]
see #39

**Pull request merged**
