### PR TITLE
add bldr and gush-block to auto tag or help to tag after a bugfix merge

### PR DESCRIPTION
**Pull request by cordoval**

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Sorry @cordoval, after all I don't intend to add this to the project.

**Comment by cordoval** [comment]
ouch, :cry:, it is ok, i will then remove the branch

**Comment by matthiasnoback** [comment]
No hard feelings I hope. It's just that I wanted to clean up the list of issues/PRs and this has no priority for me.

**Comment by cordoval** [comment]
no hard feelings. I was just trying to pitch gush and failed. :baby: I will try another time.

**Pull request closed without merging**
