### PR TITLE
tweaks to PR #22

### PR DESCRIPTION
**Pull request by xabbuh**
Tweaking the code according to @stof's review.

@matthiasnoback I didn't change the `elseif`s since you had it this way before and I thought it might be the way you prefer it. Let me know if you want me to update them as well.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks for reviewing and fixing the code! It would be great if you could change the `elseif`'s to `if`'s too: I'm usually very keen on those improvements myself, don't know why I didn't recognize the opportunity to make things simpler ;)

**Comment by matthiasnoback** [comment]
And happy new year to you too, @xabbuh and @stof!

**Comment by xabbuh** [comment]
Changed them too.

**Comment by xabbuh** [comment]
And Travis now won't try to build with Symfony 3 on PHP 5.3 and PHP 5.4.

**Comment by xabbuh** [comment]
Oh, and of course happy new year to you too @stof!

**Comment by matthiasnoback** [comment]
@xabbuh If we're done with #23 could you rebase this? Then I'll merge it and we're done for now :)

**Comment by matthiasnoback** [comment]
By the way, I intend to write a little blog post about this library - I think I've never advertised it properly...

**Comment by xabbuh** [comment]
@matthiasnoback Rebased here :) Looking forward to read your blog post. :+1:

**Pull request merged**
